# Generated by Django 4.0.6 on 2022-07-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='uuid',
            new_name='id',
        ),
    ]
